## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999

matrix:
  allow_failures:
  - julia: nightly

after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("CodecBase")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
